export const JOIN_CLASS_ERROR = 'JOIN_CLASS_ERROR';
export const JOIN_CLASS = 'JOIN_CLASS';

export const CREATE_CLASSS_SUCCESS = 'CREATE_CLASSS_SUCCESS';
export const CREATE_CLASSS_ERROR = 'CREATE_CLASSS_ERROR';